# Generated by Django 2.2.7 on 2020-01-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=120)),
                ('customer', models.CharField(max_length=120)),
                ('product_options', models.CharField(max_length=120)),
            ],
        ),
    ]
