# Generated by Django 2.2.7 on 2019-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191216_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_app',
            name='customer',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bank_app',
            name='product_options',
            field=models.CharField(max_length=120),
        ),
    ]
